upstream_package_name: wf-config
downstream_package_name: wf-config

copy_upstream_release_description: false

jobs:

- job: pull_from_upstream
  trigger: release
  dist_git_branches:
   - fedora-rawhide

- job: koji_build
  trigger: commit
  allowed_pr_authors: ["atim"]
  allowed_committers: ["atim"]
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched
